// ============================================================
//  distributions.js  —  Probability math from scratch
//  Every function here corresponds to a CS109 concept.
//  No external libraries used.
// ============================================================


// ── HELPERS ─────────────────────────────────────────────────

// Log factorial: log(n!) — exact for small n, Stirling for large n
export function logFact(n) {
  if (n <= 1) return 0;
  if (n > 20) return n * Math.log(n) - n + 0.5 * Math.log(2 * Math.PI * n);
  let s = 0;
  for (let i = 2; i <= n; i++) s += Math.log(i);
  return s;
}

// Log of n-choose-k: log C(n,k)
export function logComb(n, k) {
  if (k < 0 || k > n) return -Infinity;
  return logFact(n) - logFact(k) - logFact(n - k);
}


// ── BETA DISTRIBUTION ────────────────────────────────────────
//  Used for: Bayesian posterior over P(guard present in room)
//  Conjugate prior for Bernoulli observations.
//  After seeing k guards in n observations: Beta(k+1, n-k+1)

// Unnormalized PDF: f(x) ∝ x^(α-1)(1-x)^(β-1)
// We normalize by dividing by max when rendering
export function betaUnnorm(x, a, b) {
  if (x <= 0 || x >= 1) return 0;
  let logv = 0;
  if (a > 1) logv += (a - 1) * Math.log(x);
  if (b > 1) logv += (b - 1) * Math.log(1 - x);
  return Math.exp(logv);
}

// Mean of Beta(α, β) = α / (α+β)
export function betaMean(a, b) { return a / (a + b); }

// MAP estimate (mode) = (α-1) / (α+β-2)  for α,β > 1
export function betaMode(a, b) {
  if (a <= 1 || b <= 1) return betaMean(a, b);
  return (a - 1) / (a + b - 2);
}

// Variance of Beta(α, β) = αβ / ((α+β)²(α+β+1))
export function betaVar(a, b) {
  return (a * b) / ((a + b) ** 2 * (a + b + 1));
}

// Sample a Beta(a,b) using the Johnk method
export function betaSample(a, b) {
  // For integer params use gamma ratio; approximate with mean + noise here
  const mean = betaMean(a, b);
  const std  = Math.sqrt(betaVar(a, b));
  return Math.min(0.999, Math.max(0.001, mean + std * normalSample()));
}


// ── POISSON DISTRIBUTION ─────────────────────────────────────
//  Used for: number of guard arrivals per turn in a corridor
//  λ is estimated from Phase 1 reconnaissance observations

// PMF: P(X = k) = λ^k e^{-λ} / k!
export function poissonPMF(k, lam) {
  if (k < 0 || lam <= 0) return 0;
  return Math.exp(k * Math.log(lam) - lam - logFact(k));
}

// CDF: P(X ≤ k)
export function poissonCDF(k, lam) {
  let s = 0;
  for (let i = 0; i <= k; i++) s += poissonPMF(i, lam);
  return s;
}

// Sample from Poisson using Knuth's algorithm
export function poissonSample(lam) {
  const L = Math.exp(-lam);
  let k = 0, p = 1;
  do { k++; p *= Math.random(); } while (p > L);
  return k - 1;
}

export const poissonMean = lam => lam;
export const poissonVar  = lam => lam;


// ── EXPONENTIAL DISTRIBUTION ─────────────────────────────────
//  Used for: time (in turns) between guard patrol arrivals
//  If guards arrive at rate λ, wait time ~ Exponential(λ)
//  Mean wait = 1/λ turns

// PDF: f(x) = λ e^{-λx}
export function expPDF(x, lam) { return x >= 0 ? lam * Math.exp(-lam * x) : 0; }

// CDF: F(x) = 1 - e^{-λx}
export function expCDF(x, lam) { return x >= 0 ? 1 - Math.exp(-lam * x) : 0; }

// Sample via inverse CDF: X = -ln(U)/λ
export function expSample(lam) { return -Math.log(1 - Math.random()) / lam; }

export const expMean = lam => 1 / lam;
export const expVar  = lam => 1 / (lam * lam);


// ── NORMAL DISTRIBUTION ──────────────────────────────────────
//  Used for: noise generated by player actions
//  A loud action draws from N(μ_loud, σ²); quiet from N(μ_quiet, σ²)

// Error function approximation (Abramowitz & Stegun)
export function erf(x) {
  const t = 1 / (1 + 0.3275911 * Math.abs(x));
  const y = 1 - (((((1.061405429 * t - 1.453152027) * t)
    + 1.421413741) * t - 0.284496736) * t + 0.254829592) * t * Math.exp(-x * x);
  return x >= 0 ? y : -y;
}

// PDF: f(x) = (1/σ√2π) exp(-(x-μ)²/2σ²)
export function normalPDF(x, mu = 0, sig = 1) {
  const z = (x - mu) / sig;
  return Math.exp(-0.5 * z * z) / (sig * Math.sqrt(2 * Math.PI));
}

// CDF using erf approximation
export function normalCDF(x, mu = 0, sig = 1) {
  return 0.5 * (1 + erf((x - mu) / (sig * Math.SQRT2)));
}

// Sample N(μ, σ²) using Box-Muller transform
export function normalSample(mu = 0, sig = 1) {
  const u1 = Math.random(), u2 = Math.random();
  const z  = Math.sqrt(-2 * Math.log(u1)) * Math.cos(2 * Math.PI * u2);
  return mu + sig * z;
}


// ── BINOMIAL DISTRIBUTION ────────────────────────────────────
//  Used for: lock-picking — k successful picks in n attempts
//  p = player's skill level (updated via Beta posterior)

// PMF: P(X = k) = C(n,k) p^k (1-p)^(n-k)
export function binomPMF(k, n, p) {
  if (k < 0 || k > n) return 0;
  if (p === 0) return k === 0 ? 1 : 0;
  if (p === 1) return k === n ? 1 : 0;
  return Math.exp(logComb(n, k) + k * Math.log(p) + (n - k) * Math.log(1 - p));
}

// CDF: P(X ≤ k)
export function binomCDF(k, n, p) {
  let s = 0;
  for (let i = 0; i <= k; i++) s += binomPMF(i, n, p);
  return s;
}

export const binomMean = (n, p) => n * p;
export const binomVar  = (n, p) => n * p * (1 - p);


// ── LOGISTIC / SIGMOID ───────────────────────────────────────
//  Used for: suspicion score in Phase 3
//  P(caught | features) = σ
// Sigmoid / logistic function: σ(z) = 1 / (1 + e^{-z})
export function sigmoid(z) {
  return 1 / (1 + Math.exp(-z));
}

// Logit (inverse sigmoid): log(p / (1-p))
export function logit(p) {
  const clamped = Math.max(1e-6, Math.min(1 - 1e-6, p));
  return Math.log(clamped / (1 - clamped));
}

// Feature weights for logistic suspicion model
// P(caught | features) = σ(w · x + b)
export const SUSPICION_WEIGHTS = {
  noise:      1.8,   // how much noise player is making
  guardProx:  2.2,   // guard proximity (0–1)
  cameraOn:   1.5,   // camera active in room
  alarmOn:    3.5,   // alarm is triggered
  turnsNorm:  0.6,   // time spent in current room (normalized)
  bias:      -2.8,   // base intercept (makes p low by default)
};

// Compute suspicion score from feature vector
// Returns P(caught) ∈ [0, 1]
export function calcSuspicion({ noise = 0, guardProx = 0, cameraOn = 0, alarmOn = 0, turnsNorm = 0 }) {
  const W = SUSPICION_WEIGHTS;
  const z = W.noise    * noise
          + W.guardProx * guardProx
          + W.cameraOn  * cameraOn
          + W.alarmOn   * alarmOn
          + W.turnsNorm * turnsNorm
          + W.bias;
  return sigmoid(z);
}

// ── MLE / MAP helpers ────────────────────────────────────────
// MLE estimate of guard probability from observations
export function guardMLE(seen, total) {
  return total === 0 ? 0.5 : seen / total;
}

// MAP estimate from Beta(seen+1, total-seen+1) posterior
export function guardMAP(seen, total) {
  const a = seen + 1, b = (total - seen) + 1;
  return betaMode(a, b);
}

// Lambda for Poisson guard arrivals (smoothed from recon data)
export function guardLambda(seen, total) {
  return total === 0 ? 0.3 : (seen + 0.5) / (total + 1);
}
